# WildRobot AMP - Phase 1: Contact Rewards
# Enhanced reward shaping with foot contact and sliding penalties
# Physics-based approach (no mocap data required)

env:
  terrain: "flat"
  ctrl_dt: 0.02
  sim_dt: 0.002

  # Velocity command
  velocity_command_mode: "range"
  target_velocity: 0.7
  min_velocity: 0.5
  max_velocity: 1.0

  # Action filtering
  use_action_filter: true
  action_filter_alpha: 0.7

  # Phase signal (critical for contact rewards)
  use_phase_signal: true
  phase_period: 40
  num_phase_clocks: 2

  # Termination conditions
  min_height: 0.2
  max_height: 0.7

# Metrics to track (explicit list - cleaner than filtering)
tracked_reward_components:
  - tracking_exp_xy
  - tracking_lin_xy
  - tracking_exp_yaw
  - tracking_lin_yaw
  - forward_velocity_bonus
  - velocity_threshold_penalty
  - z_velocity
  - roll_pitch_velocity
  - roll_pitch_position
  - joint_velocity
  - joint_acceleration
  - action_rate
  - nominal_joint_position
  - joint_position_limit
  - joint_torque
  - mechanical_power
  - foot_contact
  - foot_sliding
  - foot_air_time
  - existential

# Reward weights - Phase 1C (Hybrid: Balanced rewards & penalties)
# Updated 2025-11-30: Reduce foot_sliding penalty to allow learning
# Changes from previous:
# - tracking_exp_xy: 35.0 → 100.0 (3x increase - task reward dominates!)
# - tracking_lin_xy: 14.0 → 50.0 (3.5x increase)
# - joint_acceleration: 1e-4 → 1e-8 (100x reduction - was causing 80k penalty)
# - foot_sliding: 25.0 → 12.0 (2025-11-30: Robot is "ice skating" at 5m/s sliding
#   vs 0.5m/s forward. This is normal in early training. Reduce weight to allow
#   exploration while still penalizing. Robot will learn to reduce sliding naturally.)
# Goal: Tracking reward >> penalties, creating clear "go fast" signal
# Expected: Net reward closer to 0 or positive
reward_weights:
  # Tracking sigma
  tracking_sigma: 0.25

  # === OPTION 3 (HYBRID FIX) - NEW 2025-12-01 ===
  # CRITICAL: Fix exp(-error²) being too forgiving (61% reward for 100% error!)
  #
  # FIX #1: Stricter tracking formula with steepness factor
  #   OLD: exp(-error²) gives 61% reward for 100% error
  #   NEW: exp(-3 × error²) gives 14% reward for 100% error
  tracking_steepness: 3.0  # Multiply error² by this before exp()

  # FIX #2: Velocity threshold penalty - punish moving too slowly
  #   If velocity < threshold: penalty = -50.0 × (threshold - velocity)
  #   At 0.0 m/s: penalty = -15.0 (HUGE!)
  #   At 0.3 m/s: penalty = 0.0 (threshold)
  #   At 0.7 m/s: penalty = 0.0 (no penalty)
  velocity_threshold: 0.3  # Velocity below this gets penalized (m/s)
  velocity_threshold_penalty: 50.0  # Weight for velocity threshold penalty

  # Combined Effect (Option 3):
  #   Standing (0.0 m/s): reward -12.9 (PUNISHMENT!)
  #   Slow (0.2 m/s):     reward +1.5 (barely positive)
  #   Walking (0.7 m/s):  reward +101.4 (GREAT!)
  # NEW GRADIENT: 114x difference vs 10.9x in Phase 1F!

  # === Velocity tracking - REDUCED to baseline levels ===
  # Issue 2025-11-30: Robot falling immediately with high tracking rewards
  # Reduced from 100/50 back to baseline 50/15 to allow learning balance first
  tracking_exp_xy: 50.0      # REDUCED: Was 100.0 → 50.0 (back to baseline)
  tracking_lin_xy: 15.0      # REDUCED: Was 50.0 → 15.0 (back to baseline)
  tracking_exp_yaw: 5.0      # Keep same
  tracking_lin_yaw: 1.5      # Keep same

  # === Forward Velocity Bonus - UPDATED 2025-12-01 ===
  # CRITICAL FIX: Tracking rewards were too forgiving (exp(-error^2) gives 42% reward even when moving backward!)
  # Robot discovered local minimum: get tracking reward WITHOUT moving forward
  # Solution: Add direct bonus that ONLY rewards actual forward motion
  #   - backward/stationary: 0.0 bonus (max clips negative to 0)
  #   - forward at 0.7 m/s: 0.7 × 50.0 = 35.0 bonus
  #
  # Phase 1E (10.0): Robot peaked at 0.55 m/s then degraded to 0.01 m/s - bonus too weak
  # Phase 1F (50.0): 5x stronger to match tracking magnitude (50+15=65 total)
  #   - At 0.01 m/s: bonus = 0.5 (tiny)
  #   - At 0.7 m/s:  bonus = 35.0 (huge!)
  #   - Gradient: 70x difference (was only 7x with weight=10.0)
  forward_velocity_bonus: 50.0  # INCREASED: Was 10.0 → 50.0 (5x stronger!)

  # === Stability penalties - REVERTED to baseline ===
  # Issue 2025-11-30: 40x stronger roll_pitch_position (2.0) was preventing
  # natural walking dynamics. Robot needs to lean/tilt for weight transfer!
  z_velocity: 0.1
  roll_pitch_velocity: 0.01      # REDUCED: Was 0.05 → 0.01 (back to baseline)
  roll_pitch_position: 0.05      # REDUCED: Was 2.0 → 0.05 (back to baseline, 40x reduction!)

  # === Smoothness penalties - Keep minimal to allow learning ===
  nominal_joint_position: 0.0
  joint_position_limit: 2.5
  joint_velocity: 0.0          # DISABLED: Don't double-penalize with acceleration
  joint_acceleration: 1e-8     # MINIMAL: 105k × 1e-8 = 0.001 (negligible)
  action_rate: 0.001           # Keep baseline

  # === Energy penalties (REDUCED from Phase 1B) ===
  joint_torque: 7e-8         # Was 1e-7 - reduce energy penalty
  mechanical_power: 7e-6     # Was 1e-5 - reduce energy penalty

  # === Contact rewards - ALL DISABLED for Phase 1D ===
  # 2025-11-30 Issue: Robot peaked at 9.83 reward / 0.568 m/s (step 131K)
  #                   Then degraded to 2.17 reward / -0.096 m/s (step 2.36M)
  # Root cause: foot_contact penalty (-1.14) creates barrier to walking
  #             Robot found local minimum: "freeze = +2.17 reward (safe)"
  #                                        "walk = +1-3 reward (risky)"
  # Strategy: DISABLE ALL CONTACT PENALTIES, focus ONLY on velocity tracking
  #           Let robot learn basic locomotion first
  #           Add contact refinements in Phase 2
  foot_contact: 0.0          # DISABLED - was 10.0
  foot_sliding: 0.0          # DISABLED - was 2.0
  foot_air_time: 0.0         # DISABLED - was 5.0

  # === Existential penalty ===
  existential: 1.0

training:
  num_timesteps: 20000000
  num_evals: 200
  episode_length: 600
  seed: 0

# Quick verify mode - fast sanity check before full training
# Usage: Add --quick_verify flag to training script
quick_verify:
  enabled: false              # Set to true or use --quick_verify flag
  num_timesteps: 10000        # ~20 seconds on GPU (512 envs, 10K steps)
  num_evals: 2                # Just 2 eval runs
  episode_length: 100         # Shorter episodes
  num_envs: 128               # Fewer parallel envs (faster startup)
  num_eval_envs: 16
  use_wandb: false            # Skip logging for quick tests
  render_videos: false         # TEST video rendering in quick verify!
  save_checkpoints: false     # Skip checkpointing

ppo:
  num_envs: 512
  num_eval_envs: 64
  batch_size: 256
  unroll_length: 32
  num_minibatches: 16
  num_updates_per_batch: 4

  learning_rate: 0.0003
  entropy_cost: 0.01
  discounting: 0.99
  reward_scaling: 1.0

  max_grad_norm: 0.5
  clipping_epsilon: 0.2
  normalize_observations: true
  action_repeat: 1

network:
  policy_hidden_layers: [256, 256, 128]
  value_hidden_layers: [256, 256, 128]

logging:
  use_wandb: true
  wandb_project: "wildrobot-amp"
  wandb_entity: null
  wandb_tags: ["phase1", "contact_rewards"]

rendering:
  render_videos: true
  render_height: 480
  render_width: 640

checkpointing:
  save_interval: 1000000
  keep_checkpoints: 5

validation:
  metrics:
    reward: "eval/episode_reward"
    episode_length: "eval/avg_episode_length"
  thresholds:
    reward_tolerance: 0.10
    length_tolerance: 0.10
    determinism_threshold: 0.01
