# WildRobot Locomotion Training Configuration
# Default balanced configuration for training
# Optimized for 12GB GPU (NVIDIA RTX 4070/5070)

env:
  terrain: "flat"              # Terrain type: "flat" or "rough"
  ctrl_dt: 0.02               # Control frequency: 50Hz
  sim_dt: 0.002               # Simulation frequency: 500Hz

  # Termination conditions (matches loco-mujoco's HeightBasedTerminalStateHandler)
  terminal_state_params:
    min_height: 0.2           # Minimum height before termination (fallen)
    max_height: 0.7           # Maximum height before termination (jumping/unstable)

training:
  num_timesteps: 30000000     # Total training steps (30M)
  num_evals: 200              # Number of evaluations during training (data point every ~5 min)
  episode_length: 1000        # Max steps per episode
  seed: 0                     # Random seed

ppo:
  num_envs: 1024              # Number of parallel environments (reduced from 2048 for 12GB GPU)
  num_eval_envs: 64           # Number of evaluation environments (reduced from 128)
  batch_size: 256             # Batch size for PPO updates (reduced from 512)
  unroll_length: 10           # Number of steps to unroll
  num_minibatches: 4          # Number of minibatches per update (reduced from 8)
  num_updates_per_batch: 4    # Number of gradient updates per batch

  learning_rate: 0.0003       # Adam learning rate
  entropy_cost: 0.01          # Entropy bonus coefficient
  discounting: 0.97           # Discount factor (gamma)
  reward_scaling: 0.1         # Reward scaling factor

  max_grad_norm: 1.0          # Gradient clipping threshold
  clipping_epsilon: 0.2       # PPO clipping epsilon
  normalize_observations: true # Normalize observations
  action_repeat: 1            # Action repeat (1 = no repeat)

network:
  policy_hidden_layers: [256, 256, 128]  # Policy network layers
  value_hidden_layers: [256, 256, 128]   # Value network layers

logging:
  use_wandb: true             # Use Weights & Biases
  wandb_project: "wildrobot"  # W&B project name
  wandb_entity: null          # W&B entity/team (null = personal)

rendering:
  render_videos: true         # Render evaluation video (only at end, loco-mujoco style)
  render_height: 480          # Video height
  render_width: 640           # Video width

checkpointing:
  save_interval: 1000000      # Save checkpoint every N steps
  keep_checkpoints: 5         # Number of checkpoints to keep

validation:
  # Metrics to track for validation (saved in checkpoint for automatic validation)
  # Format: {display_name: metric_key_in_training}
  metrics:
    reward: "eval/episode_reward"           # Episode reward during evaluation
    episode_length: "eval/avg_episode_length"  # Average episode length
    # Add more metrics here as needed, e.g.:
    # velocity: "eval/avg_velocity"
    # height: "eval/avg_height"
    # action_rate: "eval/avg_action_rate"

  # Validation thresholds (for pass/fail checks)
  thresholds:
    reward_tolerance: 0.10       # ±10% tolerance for reward consistency
    length_tolerance: 0.10       # ±10% tolerance for episode length
    determinism_threshold: 0.01  # Max difference for determinism check
