# Quick Training Configuration
# For fast prototyping and testing

env:
  terrain: "flat"
  ctrl_dt: 0.02
  sim_dt: 0.002

training:
  num_timesteps: 5000000      # 5M steps (faster)
  num_evals: 5
  episode_length: 1000
  seed: 0

ppo:
  num_envs: 1024              # Fewer envs (less GPU memory)
  num_eval_envs: 64
  batch_size: 256
  unroll_length: 10
  num_minibatches: 4
  num_updates_per_batch: 4

  learning_rate: 0.0003
  entropy_cost: 0.01
  discounting: 0.97
  reward_scaling: 0.1

  max_grad_norm: 1.0
  clipping_epsilon: 0.2
  normalize_observations: true
  action_repeat: 1

network:
  policy_hidden_layers: [128, 128]       # Smaller network
  value_hidden_layers: [128, 128]

logging:
  use_wandb: false            # Disable W&B for quick testing
  wandb_project: "wildrobot"
  wandb_entity: null

rendering:
  render_videos: true
  num_videos: 2
  render_height: 480
  render_width: 640

checkpointing:
  save_interval: 1000000
  keep_checkpoints: 3
